# Generated by Django 5.2.6 on 2025-10-25 21:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
