# Generated by Django 5.2.7 on 2025-10-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_slug_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
