# Generated by Django 5.2.7 on 2025-10-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Denis Lokwo', max_length=150)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('skills', models.JSONField(blank=True, help_text='List of skills', null=True)),
                ('tools', models.JSONField(blank=True, help_text='List of tools/technologies', null=True)),
                ('languages', models.JSONField(blank=True, help_text='List of languages', null=True)),
                ('interests', models.JSONField(blank=True, help_text='List of interests', null=True)),
                ('links', models.JSONField(blank=True, help_text='Dict of external links', null=True)),
                ('experience', models.JSONField(blank=True, help_text='List of experience items', null=True)),
                ('education', models.JSONField(blank=True, help_text='List of education items', null=True)),
                ('certifications', models.JSONField(blank=True, null=True)),
                ('awards', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
