# Generated by Django 5.2.6 on 2025-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_set_option4_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
