# Generated by Django 5.2.6 on 2025-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_copy_summary_to_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, help_text='Header brand text; falls back to Profile.name', max_length=120)),
                ('logo', models.ImageField(blank=True, help_text='Small logo shown in header', null=True, upload_to='site/')),
                ('default_og_image', models.ImageField(blank=True, help_text='Default OpenGraph/Twitter image', null=True, upload_to='site/')),
                ('hero_heading', models.CharField(blank=True, max_length=200)),
                ('hero_subheading', models.CharField(blank=True, max_length=300)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('analytics_measurement_id', models.CharField(blank=True, help_text='Google Analytics 4 Measurement ID', max_length=40)),
                ('consent_required', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower = earlier in featured list'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage featured section'),
        ),
    ]
