# Generated by Django 5.2.6 on 2025-10-24
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_experienceitem_more_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_eyebrow',
            field=models.CharField(blank=True, help_text='Short label above hero, e.g. role', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_roles',
            field=models.TextField(blank=True, help_text='Pipe-separated roles for home typing effect, e.g. React Developer|Django Developer|Open Source Contributor'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='calendly_url',
            field=models.URLField(blank=True),
        ),
    ]
