# Generated by Django 5.2.6 on 2025-10-24
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_sitesettings_home_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(blank=True, help_text='Contact page title heading', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subtitle',
            field=models.CharField(blank=True, help_text='Contact page subtitle/lead', max_length=300),
        ),
    ]
