# Generated by Django 5.2.6 on 2025-10-24 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='active_profile',
            field=models.ForeignKey(blank=True, help_text='Select the Profile to use for homepage avatar and global profile data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='portfolio.profile'),
        ),
    ]
