# Generated by Django 5.2.6 on 2025-10-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_sitesettings_active_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon (PNG/SVG) shown in browser tab', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Logo for dark theme (optional)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_light',
            field=models.ImageField(blank=True, help_text='Logo for light theme (optional)', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Default logo (used if variants not set)', null=True, upload_to='site/'),
        ),
    ]
