# Generated by Django 5.2.6 on 2025-10-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_sitesettings_project_featured_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceitem',
            name='company_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.JSONField(blank=True, help_text='List of quantified achievements', null=True),
        ),
    ]
