# Generated by Django 5.2.6 on 2025-10-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_experienceitem_company_url_experienceitem_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationitem',
            name='institution_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='educationitem',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='universities/'),
        ),
        migrations.CreateModel(
            name='AchievementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('metric', models.CharField(blank=True, help_text='Optional quantified metric, e.g. +30% performance', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_items', to='portfolio.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('skill', 'Skill'), ('tool', 'Tool/Tech')], default='skill', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_items', to='portfolio.profile')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('profile', 'name', 'category')},
            },
        ),
    ]
