# Generated by Django 5.2.6 on 2025-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_educationitem_institution_url_educationitem_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
