# Generated by Django 5.2.7 on 2025-10-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_sitesettings_favicon_sitesettings_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='description',
            field=models.TextField(blank=True, help_text='Optional longer description shown in the lightbox.'),
        ),
    ]
