# Generated by Django 5.2.7 on 2025-10-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_galleryitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_avatar',
            field=models.ImageField(blank=True, help_text='Override homepage avatar; if set, used instead of Profile.avatar', null=True, upload_to='site/'),
        ),
    ]
