# Generated by Django 5.2.6 on 2025-10-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_sitesettings_home_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Accessible alternative text for screen readers.', max_length=255),
        ),
    ]
