# Generated by Django 5.2.6 on 2025-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_testimonial_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at', 'id']},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_testimonials_home',
            field=models.BooleanField(default=True, help_text="Show the 'What clients say' section on the homepage"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_home_limit',
            field=models.PositiveSmallIntegerField(default=6, help_text='Max number of testimonials to show on the homepage'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on listings'),
        ),
    ]
