# Generated by Django 5.2.6 on 2025-10-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Primary brand color (e.g. #111111 or #0F172A)', max_length=9),
        ),
    ]
