# Generated by Django 5.2.6 on 2025-10-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug; auto-generated from title if left blank', max_length=200, unique=True),
        ),
    ]
