# Generated by Django 5.2.6 on 2025-10-24
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, help_text='Optional category e.g. Engineering, Tutorial', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags, e.g. django, performance, testing'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
