name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install system deps (optional, for WeasyPrint)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcairo2 \
            libpango-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libffi-dev \
            shared-mime-info
        continue-on-error: true

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Django checks
        run: python manage.py check --deploy --fail-level WARNING

      - name: Migrate DB
        run: python manage.py migrate --noinput

      - name: Run tests
        run: python manage.py test
